version: '3'
services:
  php:
    container_name: task_1
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ../:/var/www
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t /var/www
